- main.tf
> Updates bin_dir to bin2

- scripts/setup-binary.sh
> Updates download logic to avoid collisions

- .github/scripts/validate-deploy.sh
- scripts/setup-argocd.sh
- scripts/setup-binaries.sh
- test/stages/stage2-clis.tf
- variables.tf
> Adds support for installing argocd cli

- scripts/setup-argocd.sh
- scripts/setup-binaries.sh
- scripts/setup-helm.sh
- scripts/setup-igc.sh
- scripts/setup-jq.sh
- scripts/setup-yq3.sh
- scripts/setup-yq4.sh
> Tests for os type to determine which cli version to download

- .github/scripts/validate-deploy.sh
- scripts/setup-binaries.sh
- scripts/setup-gh.sh
- scripts/setup-glab.sh
- test/stages/stage2-clis.tf
- variables.tf
> Adds support for github and gitlab clis

- .github/scripts/validate-deploy.sh
- README.md
- scripts/setup-binaries.sh
- scripts/setup-kubeseal.sh
- test/stages/stage2-clis.tf
- variables.tf
Signed-off-by: Cloud-Native Toolkit <cloudnativetoolkit@gmail.com>
> Adds kubeseal to the list of downloadable clis

- .github/workflows/publish-assets.yaml
- .github/workflows/verify.yaml
- version.tf
> Updates metadata workflows

- .github/scripts/validate-deploy.sh
- .github/workflows/verify.yaml
- scripts/setup-binaries.sh
- scripts/setup-oc.sh
- test/stages/stage2-clis.tf
> Adds oc cli with alpine fix

- main.tf
- outputs.tf
- scripts/setup-binaries.sh
- scripts/setup-binary-from-tgz.sh
- scripts/setup-binary.sh
- scripts/setup-kubeseal.sh
- scripts/setup-oc.sh
- scripts/setup-rosa.sh
> Converts setup-binaries to external data source

- main.tf
> Removes unnecessary resource

- .github/scripts/validate-deploy.sh
- .github/workflows/verify.yaml
- scripts/setup-binaries.sh
- scripts/setup-ibmcloud.sh
- test/stages/stage2-clis.tf
> Adds logic to download ibmcloud cli

- .github/scripts/validate-deploy.sh
- scripts/setup-binaries.sh
- scripts/setup-ibmcloud-plugin.sh
- test/stages/stage2-clis.tf
- variables.tf
> Adds ibmcloud is plugin install

- scripts/setup-oc.sh
> Adds check for gcompat lib on alpine for oc install

- scripts/setup-oc.sh
> Handles existing kubectl soft link without failing

- scripts/setup-oc.sh
> Installs separate kubectl from https://dl.k8s.io/release

- .github/scripts/validate-deploy.sh
- scripts/setup-binaries.sh
- test/stages/stage2-clis.tf
> Adds ibmcloud ob plugin support

- module.yaml
> Updates module.yaml with registry id

- .github/scripts/validate-deploy.sh
- main.tf
- scripts/setup-binaries.sh
- scripts/setup-binary-from-tgz.sh
- scripts/setup-binary.sh
- scripts/setup-ibmcloud-plugin.sh
- scripts/setup-ibmcloud.sh
- scripts/setup-rosa.sh
> Adds debug logging to setup scripts

- README.md
- scripts/setup-binaries.sh
- Also updates the README with information about the log file
closes #42
> Writes a success message when the script is done

- README.md
- outputs.tf
- scripts/setup-binaries.sh
> Updates handling of bin_dir output to address timing issue

- .github/scripts/validate-deploy.sh
- README.md
- scripts/setup-binaries.sh
- test/stages/stage2-clis.tf
> Adds installer for ibmcloud kubernetes service plugin

- .github/scripts/validate-deploy.sh
- README.md
- scripts/setup-binaries.sh
- scripts/setup-kustomize.sh
- test/stages/stage2-clis.tf
> Adds kustomize cli to installable list

- scripts/setup-ibmcloud-plugin.sh
> Updates ibmcloud plugins if they are already installed and out of date

- .github/scripts/validate-deploy.sh
- README.md
- scripts/setup-binaries.sh
- test/stages/stage2-clis.tf
> Adds installer for ibmcloud container-registry plugin

- .github/scripts/validate-deploy.sh
- README.md
- scripts/setup-binaries.sh
- scripts/setup-gitu.sh
- test/stages/stage2-clis.tf
> Adds installer for gitu cli

- .github/scripts/validate-deploy.sh
- scripts/setup-argocd.sh
- scripts/setup-binary-from-tgz.sh
- scripts/setup-binary.sh
- scripts/setup-gh.sh
- scripts/setup-gitu.sh
- scripts/setup-glab.sh
- scripts/setup-helm.sh
- scripts/setup-ibmcloud.sh
- scripts/setup-igc.sh
- scripts/setup-jq.sh
- scripts/setup-kubeseal.sh
- scripts/setup-kustomize.sh
- scripts/setup-oc.sh
- scripts/setup-rosa.sh
- scripts/setup-yq3.sh
- scripts/setup-yq4.sh
> Verifies the cli is executable and retries once if not

- scripts/setup-argocd.sh
- scripts/setup-binaries.sh
- scripts/setup-gh.sh
- scripts/setup-glab.sh
- scripts/setup-helm.sh
- scripts/setup-ibmcloud.sh
- scripts/setup-jq.sh
- scripts/setup-kubeseal.sh
- scripts/setup-kustomize.sh
- scripts/setup-oc.sh
- scripts/setup-rosa.sh
- scripts/setup-yq3.sh
- scripts/setup-yq4.sh
> Adds support for multiple architectures (amd64 or arm64)

- .github/scripts/validate-deploy.sh
- README.md
- scripts/setup-binaries.sh
- scripts/setup-openshift-install.sh
- test/stages/stage2-clis.tf
> Adds installer for openshift-install

- scripts/setup-binaries.sh
Signed-off-by: Rich Ehrhardt <rich_ehrhardt@au1.ibm.com>
> Updated for Apple M1 architecture identification

- scripts/setup-argocd.sh
- scripts/setup-binary.sh
- scripts/setup-gh.sh
- scripts/setup-gitu.sh
- scripts/setup-glab.sh
- scripts/setup-ibmcloud.sh
- scripts/setup-igc.sh
- scripts/setup-jq.sh
- scripts/setup-kubeseal.sh
- Also forces install of jq 1.6
> Cleans up release retrieval and error handling

- scripts/setup-argocd.sh
- scripts/setup-existing.sh
- scripts/setup-gh.sh
- scripts/setup-gitu.sh
- scripts/setup-glab.sh
- scripts/setup-helm.sh
- scripts/setup-ibmcloud.sh
- scripts/setup-igc.sh
- scripts/setup-jq.sh
- scripts/setup-kubeseal.sh
- scripts/setup-kustomize.sh
- scripts/setup-oc.sh
> Adds check for existing cli before checking version

- main.tf
> Updates deprecated attributes

- scripts/setup-binaries.sh
> Updates logic to always install jq, kubeseal, and igc

- scripts/setup-binaries.sh
> Install oc and kubectl by default

- scripts/setup-argocd.sh
- scripts/setup-gh.sh
- scripts/setup-gitu.sh
- scripts/setup-glab.sh
- scripts/setup-ibmcloud.sh
- scripts/setup-igc.sh
- Changes logic for getting latest github release to use redirect header instead of api to prevent rate limiting
> Fixes issue of missing version number from lookup

- scripts/setup-rosa.sh
Signed-off-by: Indira <indira@Indiras-MacBook-Pro.local>
> Fix rosa cli download url 

- .github/workflows/verify-workflow.yaml
- scripts/setup-binary.sh
- scripts/setup-existing.sh
- scripts/setup-igc.sh
- Applies logic to igc command to ensure 1.42 minimum version
> Fixes logic to check existing binary version
